### ISSUE TITLE
EntmaxBisect forward requires unused argument

### ISSUE THREAD

**Issue by bpopeters** [deep-spin/entmax#7]
The forward method `EntmaxBisect` takes a required alpha argument. However, what is actually passed passed to the `entmax_bisect` function is `self.alpha`.

**Comment by vene** [comment]
Good catch. That argument from the forward method should be removed, IMO.

**Comment by chazzmoney** [comment]
This is fixed in code but not in the default package when installed. I think it would be worth a 1.0.1 release.

Edit: For clarity, if you install the current package and try to use EntmaxBisect class, it fails when forward is called. The existing code change fixes that. A 1.0.1 release would ensure the default package contains this fix.
